### ISSUE TITLE
Investigate high memory usage in tweakreg

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1053]
_Issue [RCAL-747](https://jira.stsci.edu/browse/RCAL-747) was created on JIRA by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly):_

tweakreg showed very high memory usage in our 18 detector combinations in B12.  I need to better understand where that comes from so that we can mitigate in future builds.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-747?focusedCommentId=678479#comment-678479):_

Isn't this a duplicate of [rcal-733](https://jira.stsci.edu/projects/RCAL/issues/RCAL-733)

**Comment by schlafly** [comment]
Yes, sorry.  In any case, it looks like
https://github.com/spacetelescope/tweakwcs/pull/196
addresses this, though I may look at additional mitigation in the tweakreg step in romancal.
