### ISSUE TITLE
astrometric_utils.create_astrometric_catalog should pick a default epoch of the time of the observation

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1107]
astrometric_utils.create_astrometric_catalog currently picks a default epoch based on meta.target.proper_motion_epoch.  I imagine that's the time when the proper motion of the target was measured, e.g., for asteroids where the proper motion may vary significantly with time.

We want to get the Gaia catalog at the time of the exposure so that the stars are appropriately shifted for their proper motions to the epoch of the observation.  That implies something more like meta.exposure.mid_time.

This was prompted by Chris asking us if we ever used mid_time, and this was the only place I could think of where we might want to use it (but we could equally well use start_time or end_time; stars don't move meaningfully during a single exposure).  But we should use some time related to the exposure and not related to a measurement of the target.

**Comment by nden** [comment]
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-778](https://jira.stsci.edu/browse/RCAL-778)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-778?focusedCommentId=694796#comment-694796):_

This was addressed as part of

#1084

.
