### ISSUE TITLE
Possible bug found in associations

### ISSUE THREAD

**Issue by WilliamJamieson** [spacetelescope/romancal#1109]
There appears to be a bug in associations here: https://github.com/spacetelescope/romancal/blob/50663a2c65fb184c278cf7faded5aee3f82e3d98/romancal/associations/lib/rules_level2.py#L152-L153

All this is doing is making a boolean comparison that is not saved. I believe this should be
```python
        if exp_type == "wfi_image":
            exp_type = "science"
```
That is setting `exp_type` to `"science"`. This however breaks a unit test here: https://github.com/spacetelescope/romancal/blob/50663a2c65fb184c278cf7faded5aee3f82e3d98/romancal/associations/tests/test_level2_candidates.py#L39
The failure report with this fix is:
```
    def test_candidate_observation(partial_args, n_asns):
        with mkstemp_pool_file(t_path("data/pool_001_candidates.csv")) as pool_path:
            cmd_args = [
                pool_path,
                "--dry-run",
                "-r",
                level2_rule_path(),
                "--ignore-default",
            ]
            cmd_args.extend(partial_args)
            generated = Main.cli(cmd_args)
>           assert len(generated.associations) == n_asns
E           assert 4 == 5
```

**Comment by nden** [comment]
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-774](https://jira.stsci.edu/browse/RCAL-774)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-774?focusedCommentId=685847#comment-685847):_

I don't think this is a bug. The exp_type in this case is strictly an analogy with the JWST pool files to create associations. We know the Roman pool files (from PSS) will be different but currently we have no examples to base the mock pool files on. Once we have realistic examples many of the selection parameters will need to be updated.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-774?focusedCommentId=686821#comment-686821):_

After thinking about this it is not a but so I'm closing this.
