### ISSUE TITLE
Fix Mosaic Basic

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1122]
_Issue [RCAL-781](https://jira.stsci.edu/browse/RCAL-781) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Match the updates to mosaic basic in RAD #&#x2060;157 

(Add the following `basic` keywords to the mosaic schema:

calibration_software_version

file_date

origin

prd_software_version

sdf_software_version

In addition, move all the `basic` tagged keywords from `mosaic_basic` to root level. )

**Comment by ddavis-stsci** [comment]
Closing this - the original rcal issue was withdrawn.
