### ISSUE TITLE
Add patch plotting utilty

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/romancal#1203]
For diagnostic purposes add a utility to show the relationship between an image and the patches deemed to overlap with the image. Also show on the same plot the subset of patches considered as candidates for a possible match, mainly for the purpose of tuning the candidate radius parameter.

**Comment by nden** [comment]
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-825](https://jira.stsci.edu/browse/RCAL-825)._
