### ISSUE TITLE
source_detection igonring output_dir when saving generated catalog

### ISSUE THREAD

**Issue by sanjibs** [spacetelescope/romancal#1213]
When running romancal.pipeline.ExposurePipeline with 
result = ExposurePipeline.call(filename,save_results=True,output_dir=dirname,
                               steps={'source_detection': {'save_catalogs':True}})

The output_dir is ignored.

**Comment by schlafly** [comment]
@mairanteodoro , can you take a look at this, for B15?  i.e., not something we want to try to get into the B14 release.

**Comment by mairanteodoro** [comment]
@schlafly Since we've moved from `SourceDetectionStep` to `SourceCatalogStep`, should we still look into this issue?

**Comment by schlafly** [comment]
Yes, thanks, I agree that since source detection is going away, we can ignore this; we should consider formally deprecating it.  Does the corresponding option work for SourceCatalog?

**Comment by mairanteodoro** [comment]
> Does the corresponding option work for SourceCatalog?

`SourceCatalogStep` does not have the option `save_catalog` (the catalog and segmentation files are always saved to disk). Running the following works properly (doesn't ignore `output_dir`):

`
ExposurePipeline.call(
    input_filename,
    save_results=True,
    output_dir=output_foldername,
)
`

**Comment by schlafly** [comment]
Great, closing, thanks.
