### ISSUE TITLE
Make sure all L3 metadata gets populated

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1235]
I think we're now at the point where we _could_ be populating all L3 metadata, and we're pretty close to the point where we are populating all L3 metadata.  We should review all of the metadata and make sure it's getting populated.  There are a few cases where I know we're lacking:

* Samantha Hoffman points out that we're not populating the l3.meta.asn.table_table field.  We should complete the population of meta.asn.
* We don't have a good mechanism for passing 'location_name' and 'product_type' to resample.  IMO we should add some optional fields to the association file that are used to specify the skycell and the product type.  Here "product type" would be something like prompt / DR for the moment, maybe eventually with additional verbiage like prompt_os or something.  Then resample would look for those and populate those fields if available.  This approach would also probably require changes to the ModelContainer to provide access to those fields.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-894](https://jira.stsci.edu/browse/RCAL-894)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-894?focusedCommentId=713932#comment-713932):_

The asn meta data in r0099101001001001001_r274dp63x31y81_prompt_F158_i2d.asdf
      pool_name: test_pool_name
      table_name: L3_mosaic_asn.json

seems to be correct.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-894?focusedCommentId=714111#comment-714111):_

We are missing telescope in the L3 data. This will need a RAD, roman_datamodels and rcal ticket and will need to be coordinated with those libraries.

We also need to fill the location_name and product_type. This can be done in resample.py and the ticket for this work is [rcal-893](https://jira.stsci.edu/browse/RCAL-893)

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-894?focusedCommentId=714999#comment-714999):_

Well telescope is now in the output products header,
in 
/Users/ddavis/src/Roman/develop/test/tmp_tc/./test_hlp_mosaic_pipeline0/r0099101001001001001_r274dp63x31y81_prompt_F158_i2d.asdf

    telescope: !<asdf://stsci.edu/datamodels/roman/tags/telescope-1.0.0> ROMAN

Closing this ticket - rcal-893 has the work to finish populating the header attributes
