### ISSUE TITLE
Romanisim L2 Product Missing Bounding Box

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1240]
_Issue [RCAL-842](https://jira.stsci.edu/browse/RCAL-842) was created on JIRA by [Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard):_

ASAB made RTB aware that L2 products made with romanisim are missing the bounding_box attribute in the gwcs object. It appears that assign_wcs in romancal does insert the bounding box. The bounding box is necessary for certain tools (e.g., imviz) to know the region over which the WCS transform is valid.

We have a workaround for the moment with the test data for the science platform, but we should add a bounding_box to the gwcs object in the next romanisim release.

**Comment by schlafly** [comment]
This is addressed here
https://github.com/spacetelescope/romanisim/pull/123
waiting for feedback.

**Comment by schlafly** [comment]
Closed in romanisim, closing here.
