### ISSUE TITLE
rename hlp to mosaic

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1247]
_Issue [RCAL-845](https://jira.stsci.edu/browse/RCAL-845) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Update the highlevel_pipeline name to be mosaic_pipline

change class from HighLevelPipeline MosaicPipeline

and the alias from roman_hlp to roman_mos? roman_mosaic? both?

**Comment by schlafly** [comment]
My two cents would be: roman_mosaic
