### ISSUE TITLE
Enable Jenkins

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#129]
_Issue [RCAL-96](https://jira.stsci.edu/browse/RCAL-96) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Enable Jenkins to run the romancal regression tests.

Set appropriate access permissions communicated separately.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Joshua Neuheisel](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jneuheisel) on [JIRA](https://jira.stsci.edu/browse/RCAL-96?focusedCommentId=510380#comment-510380):_

I'm working on this but I don't have permission to update the state of the Jira ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-96?focusedCommentId=510414#comment-510414):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) Could you add Joshua to the project.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Joshua Neuheisel](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jneuheisel) on [JIRA](https://jira.stsci.edu/browse/RCAL-96?focusedCommentId=510416#comment-510416):_

I think everything is complete. [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) please test and if everything works, close the ticket.

**Comment by jneu** [comment]
This is complete.
