### ISSUE TITLE
Running `roman_elp` leaves a fits file in the current directory.

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#1328]
I've run a number of files with the `roman_elp` (these are the simulated `uncal` shared with me by @schlafly) using a command like the following:
```
strun roman_elp <input_filename> --output_dir=<some_other_directory>
```

and now I have several `.fits` files in my current directory:
```
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 21:44 tmp_sca01.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 21:58 tmp_sca02.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 22:11 tmp_sca03.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 22:24 tmp_sca04.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 22:38 tmp_sca05.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 22:52 tmp_sca06.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 23:06 tmp_sca07.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 23:20 tmp_sca08.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 23:34 tmp_sca09.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 23 23:48 tmp_sca10.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 00:01 tmp_sca11.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 00:14 tmp_sca12.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 00:28 tmp_sca13.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 00:42 tmp_sca14.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 00:55 tmp_sca15.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 01:09 tmp_sca16.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 01:22 tmp_sca17.fits
-rw-r--r--   1 bgraham  STSCI\science   312K Jul 24 01:36 tmp_sca18.fits
```

I am assuming that each file was produced during a different run but haven't confirmed this.

**Comment by schlafly** [comment]
FYI, these describe the PSF and are created by https://github.com/spacetelescope/romancal/blob/main/romancal/lib/psf.py#L62 .  I agree that we should clean these up.

**Comment by braingram** [comment]
Thanks! It looks like it takes ~10-15 seconds for `CreatePSFLibrary` (this is only from looking at the log messages so could be off by a lot but it likely an upper bound). Some options might be:

- use a temporary file (although keeping it in scope is tricky)
- disable save (by setting `save=False` for `CreatePSFLibrary`) and cache what looks like a small (<1MB) result in memory
- disable saving and regenerate the PSF for each call (the cache would only help if the elp was run with several files from the same sca)

**Comment by schlafly** [comment]
I agree that setting save = False here is the best approach.  It was likely used in development in order to prevent that step from running every time someone wanted to make a catalog.
https://github.com/spacetelescope/romancal/blob/492c6181c2db60f7cf90cc195cae7392df822160/romancal/lib/psf.py#L172C13-L172C22
We will be eventually migrating to a PSF library stored in CRDS which will mean that this function changes to download a grid from there, but that is still several months away.
