### ISSUE TITLE
Increase `abs_separation` default value in `tweakreg`

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#1329]
The default value for `abs_separation` in romancal (0.1) matches the previous default value in jwst.

However, https://github.com/spacetelescope/jwst/pull/8445 increased this parameter to 1.0 with mention of the need for this to be 1.5x the tolerance (0.7). However a later PR added a slightly different check https://github.com/spacetelescope/jwst/pull/8476 to verify `abs_)separation > sqrt(2) * (abs_)tolerance`.

The default values in romancal could likely use some updating (and a similar check added) as I just ran into the same issue fixed by the jwst PR where running `roman_elp` on an uncal file resulted in `RuntimeError: Number of output coordinates exceeded allocation` which went away when I set `abs_separation` to 1.0.

The failed filed were simulated images shared with me by @schlafly:
```
['r0000101001001001001_01101_0002_WFI10_uncal.asdf' and 'r0000101001001001001_01101_0003_WFI10_uncal.asdf']
```

**Comment by mcara** [comment]
Current defaults:
```
separation = float(default=1.0) # Minimum object separation in arcsec
tolerance = float(default=0.7) # Matching tolerance for xyxymatch in arcsec
abs_separation = float(default=0.1) # Minimum object separation in arcsec when performing absolute astrometry
abs_tolerance = float(default=0.7) # Matching tolerance for xyxymatch in arcsec when performing absolute astrometry
 ```

For absolute alignment, the settings are bad, as mentioned by @braingram, resulting in multiple sources being within the tolerance region, while `xyxymatch` allocates enough memory for just 1 match, resulting in the above error. For relative alignment settings are "better", however, a tolerance of 0.7 arcsec is kind of large, IMHO.

**Comment by schlafly** [comment]
If you want to suggest a different value, Mihai, please do.  In practice we don't use relative alignment and just align to Gaia all of the time, so it is somewhat future-proofing rather than something we actually use.

Practically we expect our ultimate alignment to be ~1 mas, so after tweakreg if we're doing worse than 0.1" for brightish stars something is pretty bad.  Before tweakreg alignment errors of a few pixels seem plausible to me.

**Comment by mcara** [comment]
> ... Before tweakreg alignment errors of a few pixels seem plausible to me.

=> `tolerance = (a few pixels) * pixel_scale` (and round up to a more round value)
