### ISSUE TITLE
Update source catalog results with tweaked astrometry

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1371]
_Issue [RCAL-895](https://jira.stsci.edu/browse/RCAL-895) was created on JIRA by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro):_

We create the source catalog before tweakreg so that we can use the measured positions to update the WCS of the image. The source catalog also contains ra/dec for the sources based on the pre-tweakreg WCS, but we should update those positions to use the post-tweakreg WCS once we have it.

- Original issue: #1369

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-895?focusedCommentId=714137#comment-714137):_

[Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly)
Few questions:
 * should we add new columns to the current cat file table with the tweaked coordinates?
 * should we only update the cat file when running the ELP? Or should we update the file when running TweakRegStep (checking for meta.tweakreg_catalog_name)?
 * I assume the tweaked WCS should be applied to the results of the PSF astrometry, correct?

These are the columns present in the current cat file table:
```java
'label','xcentroid','ycentroid','ra_centroid','dec_centroid','aper_bkg_flux','aper_bkg_flux_err','aper30_flux','aper30_flux_err','aper50_flux','aper50_flux_err','aper70_flux','aper70_flux_err','aper_total_flux','aper_total_flux_err','CI_50_30','CI_70_50','CI_70_30','flags','is_extended','sharpness','roundness','nn_label','nn_dist','isophotal_flux','isophotal_flux_err','isophotal_area','semimajor_sigma','semiminor_sigma','ellipticity','orientation','sky_orientation','ra_bbox_ll','dec_bbox_ll','ra_bbox_ul','dec_bbox_ul','ra_bbox_lr','dec_bbox_lr','ra_bbox_ur','dec_bbox_ur','flag_psf','x_psf','x_psf_err','y_psf','y_psf_err','flux_psf','flux_psf_err' ```

**Comment by schlafly** [comment]
Thanks Mairan.  Let's update all of the ra/decs.  i.e., ra/dec_centroid,
ra/dec_bbox_*.  Let's only do it for the ELP---I guess that means an
additional argument to tweakreg that the ELP sets?  Yes; I don't currently
see an ra_psf, dec_psf in your list, but we should add that if we don't
have it, with the values from the updated astrometry.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-895?focusedCommentId=714327#comment-714327):_

PR for review: #1373
