### ISSUE TITLE
Integrate Tag approach into Roman pipelines

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#139]
_Issue [RCAL-100](https://jira.stsci.edu/browse/RCAL-100) was created on JIRA by [Perry Greenfield](https://jira.stsci.edu/secure/ViewProfile.jspa?name=perry):_

Fold in the use of tagged ASDF data files into the Roman pipeline, much of the work on this will be in the roman_datamodels package, but some will be with the romancal package as well

**Comment by nden** [comment]
Duplicate with #211 
Closed in #212

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-100?focusedCommentId=528911#comment-528911):_

Resolved in #212
