### ISSUE TITLE
Make mosaic file names more flexible

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1390]
I wanted to make an output skycell file with the name "blah.asdf."  That's currently not allowed since that product name doesn't fit the regex pattern here:
https://github.com/spacetelescope/romancal/blob/26d03937dfc7d77b6dc5ba0dbf64809403a78f47/romancal/pipeline/mosaic_pipeline.py#L101-L104

It seems to me that we should just let the user specify the output file name and not require that it fit a particular pattern.  I would better understand forcing an additional _i2d suffix (as we do), but I don't think we need to force the skycell name to occur in a particular place and could just use whatever the user specified.

**Comment by ddavis-stsci** [comment]
That looks like very old code. I can rename the output by updating the asn product name or by setting the output file
`--output_file         File to save output to.`
Currently the skycell name come from the "target" field in the association not the product name
`skycell_name = input.asn["target"]`

**Comment by schlafly** [comment]
Yeah, I agree that another approach would be to just delete the skycell_file_name concept, which is only used to flag against an unimplemented feature.  I agree that there are other ways to set the output file name, but presently things crash and burn if you set an invalid product name, and that doesn't seem like it needs to be the case.

**Comment by ddavis-stsci** [comment]
Can you send me the commands to crash the program? I seem to be able to put in arbitrary product names.

**Comment by schlafly** [comment]
asn_from_list r0000101001001001001_01101_0001_WFI01_cal.asdf r0000101001001001001_01101_0002_WFI01_cal.asdf -o asn.json --product-name l3
now manually go in and add a target = "r274dp63x32y80" into asn.json
strun roman_mos asn.json

```
----------------------------------------------------------------------
ERROR RUNNING STEP 'MosaicPipeline':
    list index out of range
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eschlafly/opt/miniconda3/envs/roman/lib/python3.12/site-packages/stpipe/cli/strun.py", line 24, in main
    Step.from_cmdline(sys.argv[1:])
  File "/Users/eschlafly/opt/miniconda3/envs/roman/lib/python3.12/site-packages/stpipe/step.py", line 191, in from_cmdline
    return cmdline.step_from_cmdline(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eschlafly/opt/miniconda3/envs/roman/lib/python3.12/site-packages/stpipe/cmdline.py", line 395, in step_from_cmdline
    step.run(*positional)
  File "/Users/eschlafly/opt/miniconda3/envs/roman/lib/python3.12/site-packages/stpipe/step.py", line 524, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/eschlafly/projects/roman/romancal/romancal/pipeline/mosaic_pipeline.py", line 103, in process
    skycell_root = re.findall("^[^%\n\r]*_", product_name)[0]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-906](https://jira.stsci.edu/browse/RCAL-906)._
