### ISSUE TITLE
Remove units from mosaic level pipeline

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1406]
_Issue [RCAL-911](https://jira.stsci.edu/browse/RCAL-911) was created on JIRA by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly):_

Remove units from the mosaic level pipeline.  This involves updates to rad (removing units from schemas), roman_datamodels (removing units from the data models) and romancal (removing units from the pipeline).  The mosaic level pipeline uses fewer units than the ELP, so my expectation is that this will be much less involved than there.  I believe it uses no reference files with units (though the photmjysr column in the ELP files carry units), so that will also make it easier.  We should assume for the moment that that column will continue to have units, and so the mosaic level pipeline should remove them via .value; a later update to the ELP will remove those updates and require an update to the mosaic level pipeline to compensate.

I've given the epic as mosaic images in B15 since this touches the HLP, but we should migrate to a B16 epic when available.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-911?focusedCommentId=722842#comment-722842):_

We are removing units from the data arrays, i.e. removing quantities from the files. However, the data units is valuable information. How is this info stored in the files or is it TBD?

**Comment by schlafly** [comment]
TBD.  Tyler and I talked a little about this.  We are going to continue to have it in the rad schemas following Brett's suggestion here:
https://github.com/spacetelescope/rad/pull/438
Brett gives an example of how to access that information for Roman data models.  It seems to me that the schema contains enough information that we should consider putting the whole thing in the asdf files, rather than just a link, if we do not currently do that.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-911?focusedCommentId=732740#comment-732740):_

The results from removing the units are reported here: <https://innerspace.stsci.edu/pages/viewpage.action?pageId=528888606>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-911?focusedCommentId=743097#comment-743097):_

PRs:
 * #1445
 * spacetelescope/rad#485
 * spacetelescope/roman_datamodels#405
