### ISSUE TITLE
create_s_region, add_s_region, and create_footprint duplicate stcal functions

### ISSUE THREAD

**Issue by emolter** [spacetelescope/romancal#1466]
The `create_s_region` function duplicates the functionality of stcal's `compute_s_region_keyword` https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L710 and should be replaced with the stcal version.

The `create_footprint` and `add_s_region` functions together duplicate the behavior of stcal's `compute_s_region_imaging` https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L639 and a small stcal refactor that splits `compute_s_region_imaging` in two could cover the direct use of `create_footprint` in Romancal resample without affecting the way `compute_s_region_imaging` is currently used in jwst.

Discovered while investigating https://github.com/spacetelescope/romancal/issues/1455

**Comment by mairanteodoro** [comment]
@emolter Draft PR: https://github.com/spacetelescope/romancal/pull/1493
