### ISSUE TITLE
stpreview leading to nightly / nightly_numpy regtest failures

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/romancal#1479]
We're not including stpreview as a dependency for romancal, and only including it as an sdp dependency here:
https://github.com/spacetelescope/romancal/blob/2ee4608f6551538b7c09ee48d5d12ec0b38b5d36/pyproject.toml#L71

However, the regression tests require stpreview, leading to failures like this one:
https://github.com/spacetelescope/RegressionTests/actions/runs/11584533987/job/32251935387#step:28:749

We probably just want to add stpreview either as a test or an overall dependency?

Zach, I've assigned you since you wrote stpreview and may know why we didn't make it a real dependency; I don't remember.

**Comment by schlafly** [comment]
I think we just need to add sdp to the package_extras here and here:
https://github.com/spacetelescope/RegressionTests/blob/8fc59cf6b4b800918dfb83fc5bcb8ccd5e326c5a/.github/workflows/romancal.yml#L124
https://github.com/spacetelescope/RegressionTests/blob/8fc59cf6b4b800918dfb83fc5bcb8ccd5e326c5a/.github/workflows/romancal.yml#L147

**Comment by zacharyburnett** [comment]
good idea, but if `stpreview` is required by tests then we should add it to the `test` extra: https://github.com/spacetelescope/RegressionTests/actions/runs/11667824266/job/32486193076

**Comment by zacharyburnett** [comment]
oops, I just realized I pushed that change to `romancal@main` and not a PR branch 😅 well it's small enough to be innocuous
