### ISSUE TITLE
Roman Ramp fit unit tests-preliminary setup

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#148]
_Issue [RCAL-106](https://jira.stsci.edu/browse/RCAL-106) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Once the ramp fitting step is running in the roman cal pipeline update the JWST unit tests for the roman ramp fitting case.

**Comment by nden** [comment]
Ramp_fitting regression test added in #276.
