### ISSUE TITLE
devdeps failing with "ModuleNotFoundError: No module named 'pyarrow'"

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#1481]
https://github.com/spacetelescope/romancal/actions/runs/11598260944/job/32293762396#step:10:922

I believe this may be due to the use of a development version of astropy.

This also appears in the downstream/devdeps testing in stcal:
https://github.com/spacetelescope/stcal/actions/runs/11597106821/job/32289791188#step:10:745

Is it necessary/useful to test all of these formats?
https://github.com/spacetelescope/romancal/blob/2f7d0652d17e06207cc6c6263818ab339a1b17db/romancal/tweakreg/tests/test_astrometric_utils.py#L484-L493
It seems like more a test of astropy than anything romancal related.

**Comment by braingram** [comment]
@mairanteodoro is there a requirement to test all these formats? If so we may need to add some more test dependencies.

**Comment by mairanteodoro** [comment]
> @mairanteodoro is there a requirement to test all these formats? If so we may need to add some more test dependencies.

Not that I know of, @braingram.
I think we can reduce that list down to the ones we use the most (i.e., asdf & fits, as far as I'm concerned).

**Comment by schlafly** [comment]
Confirming, yes, we need only support a small number of formats, maybe fits and ecsv.  asdf is also good though I actually don't know what schema would be being used for that catalog.  @mairanteodoro , if you have time, cleaning this up to be more minimal so it doesn't affect devdeps testing would be great, thanks.

**Comment by mairanteodoro** [comment]
Work done in [PR#1496](https://github.com/spacetelescope/romancal/pull/1496).
