### ISSUE TITLE
Update jump unit tests for Roman data

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#154]
_Issue [RCAL-114](https://jira.stsci.edu/browse/RCAL-114) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Adapt the JWST jump unit tests to the Roman Jump step

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/RCAL-114?focusedCommentId=544244#comment-544244):_

Work on this ticket is blocked, as the roman_datamodels library's code needs some work for the tagged objects and metadata. (Similarly for RCAL-178: " Implement jump step via stpipe ")

**Comment by nden** [comment]
@dmggh See [this comment](https://github.com/spacetelescope/romancal/pull/267#discussion_r688440363) . Please post here if you actually see errors when **running** the code.
