### ISSUE TITLE
Configure more comprehensive PEP8 checks

### ISSUE THREAD

**Issue by nden** [spacetelescope/romancal#175]
Romancal uses flake8 with a configuration in setup.cfg.
Follow the examples in spacetelescope/jwst#5805 and spacetelescope/jwst#5812 (the changes to setup.cfg) to improve the flake8 checks in romancal.

**Comment by ddavis-stsci** [comment]
Most of these seem to be implemented 
E021, E202, E211 spaces and ')' or '(', Check
E221 & E222 multiple spaces before and after operator, Check
E271 & E272 multiple spaces before and after keyword, Check
E273 & E274 TAB before and after keyword, Check
E275 Missing whitespace after keyword, Check
E701 & E702 Multiple statements on one line, Check
E703 Statement ends with a semicolon, Check
E704 Add this
E712 Comparison to true should be...
E713 Test for membership should be 'not in', Check
E714 Test for object identity should be 'is not', Check

E231 | Missing whitespace after ',', ';', or ':', Check
E241 | Multiple spaces after ',' Add
