### ISSUE TITLE
review metadata for WFI imaging, prism, & grating modes

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#201]
_Issue [RCAL-146](https://jira.stsci.edu/browse/RCAL-146) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

calibration at level 2 is the same for spectroscopy mode and imaging mode, but there may be differences in the metadata that is used or needed. Make sure that we understand the basic differences, even if they only apply to reference file creation.

The biggest difference is a separate dark reference file which is needed for this mode

**Comment by ddavis-stsci** [comment]
RCAL-146 closed and items reviewed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) on [JIRA](https://jira.stsci.edu/browse/RCAL-146?focusedCommentId=522837#comment-522837):_

refer back to the exp_type conversation here for the values we are using and have been sent to project: <https://innerspace.stsci.edu/display/ROMAN/EXP_TYPE+Discussion>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-146?focusedCommentId=523102#comment-523102):_

||Attribute||Imaging||Grism||Prism||
|meta.exposure.type|WFI_F???|WFI_GRISM|WFI_PRISM|
|meta.instrument.optical_element|F???|GRISM|PRISM|
|meta.instrument.detector|WFI01|WFI01|WFI01|
|meta.observation.date|2021-02-01|2021-02-01|2021-02-01|
|meta.observation.time|00:00:00.000|00:00:00.000|00:00:00.000|
|meta.observation.ma_table_name|HLIS|HLIS|HLIS|

 
 Reference files needed information:

Dark:
 * meta.instrument.detector=WFI01
 * meta.observation.ma_table_name=HLIS
 * meta.observation.date=2021-02-01
 * meta.observation.time=00:00:00.000

Flat:
 * meta.instrument.detector=WFI01
 * meta.exposure.type='WFI_PRISM'
 * meta.observation.date=2021-02-01
 * meta.observation.time=00:00:00.000

blah blah
