### ISSUE TITLE
Test to show WFI ingest (SOC-628.3)

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#207]
_Issue [RCAL-150](https://jira.stsci.edu/browse/RCAL-150) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

An automated test to show the ingest WFI Level 1 data products for the imaging mode

**Comment by ddavis-stsci** [comment]
This was supposed to be in the RDADS project **not** RCAL, Closing the issue here.
