### ISSUE TITLE
Assess Need For Dark NaN Flag

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#236]
_Issue [RCAL-170](https://jira.stsci.edu/browse/RCAL-170) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

In dark current correct, any pixel values in the dark reference data that are set to NaN will have their values reset to zero before being subtracted from the science data, which
will effectively skip the dark subtraction operation for those pixels. However, there is no flag value set for these Dark NaN pixels. We should decide if that is the correct course of action, or if they should be flagged, and if so, with which flag.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-170?focusedCommentId=536212#comment-536212):_

[Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) and [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) - is there an Epic for this work?  And (I know you are tired of hearing it) is the Epic connected to a Saga?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-170?focusedCommentId=567305#comment-567305):_

[Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) Given RCAL-185 and because by definition romancal needs to do what jwst does, do you think this is still relevant?

I suggest we close it.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-170?focusedCommentId=572865#comment-572865):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) - has a decision been made to keep this open or close it, based on your comment above

**Comment by ddavis-stsci** [comment]
To update this issue we are still planning to discuss this with INS in more depth, from a SLACK exchange,
```
At some point in the future we need to get back to NaNs in reference files and discuss their use.
At the moment for linearity we are replacing them with zeros, iirc, and for this one operation we have to make a copy of the data array.
But perhaps other steps have better use of NaNs...

```

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-170?focusedCommentId=599753#comment-599753):_

INS decided there will be no NaNs in reference files.
