### ISSUE TITLE
Link github with JIRA

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#24]
_Issue [RCAL-22](https://jira.stsci.edu/browse/RCAL-22) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Configure the bot to link the new github repository with the JIRA RCAL project

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by eslavich** [comment]
Confirming that the bot is working in the other direction...

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489923#comment-489923):_

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Please add the "Roman" mission tag to this ticket.  

Thanks

Erica

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=489935#comment-489935):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) I added the Roman mission tag but this ticket is in the RCAL project. Isn't it all Roman?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490010#comment-490010):_

It is all Roman work in RCAL, but for consistency in queries it is best to have the mission field filled in for each Jira issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490035#comment-490035):_

I requested a service account for the new bot [here](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=ae13a70adb3f1450fb50f9baae96195d).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490139#comment-490139):_

Also I initially required it in my status report query.  I fixed that part, but as [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) wrote, it is helpful for consistency.  Someone who knows about the Mission tag but doesn't necessarily know all the projects can still see Roman work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490155#comment-490155):_

I was just wondering if there's a way to automatically set that flag on everything in RCAL. It's one less thing to remember.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490166#comment-490166):_

That can be done through automations and I will do that for the 4 Roman projects that I can.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=490239#comment-490239):_

[Melissa Russ](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mlruss) - thank you

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=492914#comment-492914):_

The service account and mailbox have been created, submitted [another ticket](https://stsci.service-now.com/stars?id=ticket&table=sc_req_item&sys_id=09dc498fdb042c90591e79fdae9619b2) to grant the necessary privileges on RCAL and add the metadata fields to the project's screens.

**Comment by eslavich** [comment]
One more test.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-22?focusedCommentId=493942#comment-493942):_

The bot is up and running and initially created 22 issues on GitHub (including for this one).  It runs as a cron job at 5 minute intervals.
