### ISSUE TITLE
Fix Jenkins Failures With RAD 0.2.0 & RDM 0.3.0 & Create Tickets

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#245]
_Issue [RCAL-175](https://jira.stsci.edu/browse/RCAL-175) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Romancal is failing to build with the latest versions of RAD & RDM. This ticket is to fix that (by linking to earlier versions of RDM & RAD) and to create tickets for getting RomanCAL building with the  up to date versions.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-175?focusedCommentId=535995#comment-535995):_

The fix is implemented, tested, and merged into romancal via PR 246: #246

**Comment by PaulHuwe** [comment]
Closed & fixed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-175?focusedCommentId=536050#comment-536050):_

I have documented all the work needed to get RomanCAL & CRDS up to snuff with RAD & RDM.
