### ISSUE TITLE
Implement Jump step via stpipe

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#258]
_Issue [RCAL-178](https://jira.stsci.edu/browse/RCAL-178) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Implement the Jump step code running via stpipe.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/RCAL-178?focusedCommentId=542045#comment-542045):_

Work on this ticket is blocked, awaiting updates in the datamodels library. Before I began work on this ticket, I  wanted to first verify that I could still run the flat field step (as I had first done several months ago), to make sure that the underlying libraries for running steps still worked. I could not run the flat step, as the updated datamodels library was not (and still is not) available,. As a result, I never reached the point of submitting a PR for RCAL-178.

**Comment by dmggh** [comment]
Using the latest L2 file and mask file, I am able to run the flat field step, which indicates that the data models library was not a factor. I will file a PR, and proceed with work on RCAL-178

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/RCAL-178?focusedCommentId=544243#comment-544243):_

Work on this ticket is blocked, as the roman_datamodels library's code needs some work for the tagged objects and metadata. (Similarly for RCAL-114: " Jump unit tests." )
