### ISSUE TITLE
Create Regression Tests for DQ

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/romancal#265]
DQ_Init step needs regression tests in addition to the pytests.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-182](https://jira.stsci.edu/browse/RCAL-182)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-182?focusedCommentId=546723#comment-546723):_

I have an initial implementation working locally (sans CRDS call), with artifactory files created. I cannot work on this further until CRDS is updated.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-182?focusedCommentId=547107#comment-547107):_

Mask files are in CRDS, and this work is now in PR:
#290

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-182?focusedCommentId=547250#comment-547250):_

Test files have been created and place din Artifactory, PR comments have been addressed, PR approved and merged.
