### ISSUE TITLE
Add dark current regression tests

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#272]
_Issue [RCAL-186](https://jira.stsci.edu/browse/RCAL-186) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Create regression tests

**Comment by ddavis-stsci** [comment]
Code merged closing the issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-186?focusedCommentId=566017#comment-566017):_

#392
