### ISSUE TITLE
Update Ramp Readnoise code to RDM

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#277]
_Issue [RCAL-189](https://jira.stsci.edu/browse/RCAL-189) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Update ramp steps & tests for RDM readnoise

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-189?focusedCommentId=545685#comment-545685):_

This may be covered by PR

#276

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis)? [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm)?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-189?focusedCommentId=545689#comment-545689):_

I don't think the readnoise is wrapped up in stpipe. Or maybe I should say that stpipe is not dependent on the rdm code and so these should be separate tasks/tickets.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-189?focusedCommentId=545847#comment-545847):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis), [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) - this needs an Epic parent - let me know if we don't have what we need

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-189?focusedCommentId=563651#comment-563651):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Is there any work to be done for this ticket?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-189?focusedCommentId=563658#comment-563658):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva)I don't see anything in the code that needs to be updated, so I'd close this one.

**Comment by ddavis-stsci** [comment]
Closing this ticket since I don't see any updates that need to be made.
