### ISSUE TITLE
Update Jump Readnoise Code to RDM

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#278]
_Issue [RCAL-190](https://jira.stsci.edu/browse/RCAL-190) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Update jump steps & tests for readnoise RDM interface

**Comment by ddavis-stsci** [comment]
This appears to be closed as well.
