### ISSUE TITLE
Update Ramp Gain Code to use RDM

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#279]
_Issue [RCAL-191](https://jira.stsci.edu/browse/RCAL-191) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Update ramp steps & tests for gain RDM interface

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-191?focusedCommentId=545642#comment-545642):_

Anything more than what is in this PR?

#276

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-191?focusedCommentId=545682#comment-545682):_

Hrmm, it looks like that may have everything for ramp  (particularly since ramp has no tests). I'll leave it to [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) and [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) to confirm.

**Comment by ddavis-stsci** [comment]
Not sure why this was reopened it should be closed.
