### ISSUE TITLE
Tests for Roman dark schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#28]
_Issue [RCAL-27](https://jira.stsci.edu/browse/RCAL-27) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Write a test module to test the dark reference schema (rcal-3) first verifying failure when the schema items are not present and passing once those elements are in place. This can be based partially on the JWST test test_schema.py in datamodes/tests.

**Comment by ddavis-stsci** [comment]
Schema tests will be done in stdatamodels.
