### ISSUE TITLE
Update Jump Code to Use RDM Gain

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#280]
_Issue [RCAL-192](https://jira.stsci.edu/browse/RCAL-192) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Update jump steps & tests for gain RDM interface

**Comment by ddavis-stsci** [comment]
https://jira.stsci.edu/browse/RCAL-192 was closed on Dec 20, 2021

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-192?focusedCommentId=563650#comment-563650):_

There's no work to be done here. Should we delete it or am I missing something?
