### ISSUE TITLE
Update Mask Code in Ramp, Flat, and Jump step and tests to RDM

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#281]
_Issue [RCAL-193](https://jira.stsci.edu/browse/RCAL-193) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

RDM mask updates for flat, ramp, jump & tests.

**Comment by ddavis-stsci** [comment]
https://jira.stsci.edu/browse/RCAL-193 was closed Jan 15  2022

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-193?focusedCommentId=563648#comment-563648):_

[Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) Could you elaborate on the work for this ticket? Is there something still to be done?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-193?focusedCommentId=563662#comment-563662):_

The ticket was made to R&D and implement changes needed for RDM implementation of Ramp, Jump, and Flat to check their tests and utilities given changes made for masks (and to catch up in general).

 

Eyeballing it now:

RDM is lacking tests for the Ramp utilities 
The flat tests need updating to match the other steps - and possibly the utilities can be updated to match the rest
I am guessing nothing needs to be done for Jump



I think the other changes were already made - nothing else is jumping out at me at present.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-193?focusedCommentId=566069#comment-566069):_

This work is implemented in RDM PR 59:  spacetelescope/roman_datamodels#59

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-193?focusedCommentId=566096#comment-566096):_

I have created a corresponding RCAL ticket to update the tests in RomanCAL that use maker functions.

<https://jira.stsci.edu/browse/RCAL-290>
