### ISSUE TITLE
Enable pipeline testing infrastructure on Travis

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#29]
_Issue [RCAL-17](https://jira.stsci.edu/browse/RCAL-17) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Enable the Roman pipeline testing on Travis. Include a simple test to verify it works.

**Comment by jdavies-st** [comment]
A good way to do this would be to copy the `.travis.yml` script from

https://github.com/spacetelescope/jwst

and just keep 4 jobs: 

1. latest dependencies
2. code style check
3. security check
4.build distribution check

You may have to update test dependencies.

Documentation build job would be good to have too once documentation is set up.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-17?focusedCommentId=499074#comment-499074):_

We will be using Github Actions. Superseded by RCAL-61.
