### ISSUE TITLE
Update artifactory location for regression tests

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#293]
_Issue [RCAL-199](https://jira.stsci.edu/browse/RCAL-199) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Update the reference file location for the romancal reference files. So files point to romancal-pipeline while the locations in artifactory should be

roman-pipeline

or

roman-pipeline-results

**Comment by ddavis-stsci** [comment]
Close this as a duplicate of #294
