### ISSUE TITLE
Implement Persistence RDM Support

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#304]
_Issue [RCAL-207](https://jira.stsci.edu/browse/RCAL-207) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Implement datamodel support for persistence reference files in roman_datamodels. 

Create maker utility for the data model.

Create tests for the maker utility.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) on [JIRA](https://jira.stsci.edu/browse/RCAL-207?focusedCommentId=549448#comment-549448):_

[Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) and [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis)  a reminder that we are not implementing persistence correction support in romancal and wont need a datamodel for reference files.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-207?focusedCommentId=549458#comment-549458):_

[Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) So we can drop this and all the trap* datamodel tickets?

**Comment by sosey** [comment]
yes please :)
