### ISSUE TITLE
Tests for SOC-604 (WFI imaging Level 2 processing)

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#344]
_Issue [RCAL-242](https://jira.stsci.edu/browse/RCAL-242) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Write tests to cover SOC-604. This includes DMS-86, 87, 88, 89.

The level 1 pipeline steps need to include
 * dq
 * saturation
 * linearity
 * dark
 * jump
 * ramp
 * flat correction

_success criteria:_
 * steps listed above are marked as having been performed in the data and logging
 * sci, dq, error arrays exist in the output product
 * a simple GWCS model exists
Additions
* Attribute for total exposure time exists, <https://jira.stsci.edu/browse/RDM-2041>

The following error arrays exist in the product:
* ERR - general error
* VAR_FLAT
* VAR_POISSION
* VAR_READNOISE

WCS object exists and
* can be found when the file is opened
* it contains basic information

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=559585#comment-559585):_

I have this mostly working, but the wcs confirmation requires wcs objects being added to sample L2 files.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=560175#comment-560175):_

Block lifted with updates on cal_logs tests and the pipeline. Work on this has resumed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=560178#comment-560178):_

This is now ready for review. The script and test file are available in: 

TEST_DATA/phuwe/b0.4/image_l2_test/

(in the roman directory on central store)

To run, type:
./test_wfi_image.py r0008308002010007027_06311_0019_WFI01_cal.asdf 
(or some other l2 file name).

The level 2 file in the directory's provenance is:
- Level 1 file made by INS and available on central store
- Run through the romancal pipeline (all steps) to generate output for testing

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=560267#comment-560267):_

Updated the script with some code cleanup.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=561207#comment-561207):_

I have been directed to refactor this as a regtest, and I have begun that work.

**Comment by ddavis-stsci** [comment]
In release 0.5.0

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-242?focusedCommentId=562382#comment-562382):_

Confirmed and merged.
