### ISSUE TITLE
Tests for SOC-622 (WFI spectroscopic Level 2 processing)

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#345]
_Issue [RCAL-243](https://jira.stsci.edu/browse/RCAL-243) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Write tests to cover SOC-622. This includes DMS-90, 91, 92, 93.

The level 1 pipeline steps need to include
 * dq
 * saturation
 * linearity
 * dark
 * jump
 * ramp
 * flat correction

_success criteria:_
 * steps listed above are marked as having been performed in the data and logging
 * sci, dq, error arrays exist in the output product
 * a simple GWCS model exists

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=558307#comment-558307):_

I have started working on this, but it is blocked by both pipeline development and wcs implementation.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=558935#comment-558935):_

I have put an initial script for this (and a sample L2 file from INS) in:

TEST_DATA/phuwe/b0.4/grism_l2_test

(in the roman directory on central store)

To run, type:
>./test_wfi_spec_image.py r0019106003005004023_03203_0034_WFI01_cal.asdf

(or some other l2 file name).

I am looking for some feedback on the output and tests.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=559584#comment-559584):_

I have this mostly working, but the wcs confirmation requires wcs objects being added to sample L2 files.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=560176#comment-560176):_

Block lifted with updates on cal_logs tests and the pipeline. Work on this has resumed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=560177#comment-560177):_

This is now ready for review. The script and test file are available in: 

TEST_DATA/phuwe/b0.4/grism_l2_test/

(in the roman directory on central store)

To run, type:
./test_wfi_spec.py r0019106003005004023_03203_0034_WFI01_cal.asdf 
(or some other l2 file name).

The level 2 file in the directory's provenance is:
- Level 1 file made by INS and available on central store
- Run through the romancal pipeline (all steps) to generate output for testing

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=560268#comment-560268):_

Updated the script with some code cleanup.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=561208#comment-561208):_

I have been directed to refactor this as a regtest, and I will begin doing that once I have the image test converted.

**Comment by ddavis-stsci** [comment]
in release 0.5.0

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=562437#comment-562437):_

These tests are implemented in RCAL PR-385:

#385

All requisite files are in artifactory.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-243?focusedCommentId=562503#comment-562503):_

Confirmed and merged.
