### ISSUE TITLE
Update Tests of Calsteps

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#354]
_Issue [RCAL-247](https://jira.stsci.edu/browse/RCAL-247) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Update the tests of RAD for the additions to the list of required calsteps.

**Comment by ddavis-stsci** [comment]
the parent ticket https://jira.stsci.edu/browse/RCAL-247  was closed on Jan 15, 2022

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-247?focusedCommentId=566443#comment-566443):_

Thsi is implemented in RDM PR-60: spacetelescope/roman_datamodels#60

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-247?focusedCommentId=566485#comment-566485):_

These updates require creation of new regression test files - doing that now.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-247?focusedCommentId=566577#comment-566577):_

All regression tests pass, all files needing updates (over a dozen) are updated and in artifactory.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-247?focusedCommentId=566578#comment-566578):_

Increased story points to reflect the work with the regression test files.
