### ISSUE TITLE
Attributes rst file for epic RCAL-248

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#373]
_Issue [RCAL-257](https://jira.stsci.edu/browse/RCAL-257) was created on JIRA by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm):_

This is a child ticket for the attributes rst file for epic RCAL-248 "Create Documentation For Roman_Datamodels"

**Comment by ddavis-stsci** [comment]
This was done on May 20, 2022 so closing this issue.
