### ISSUE TITLE
Test artifacts for SOC-604 from Test string

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#379]
_Issue [RCAL-263](https://jira.stsci.edu/browse/RCAL-263) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

After running the tests for SOC-604 on the Test string add the log outputs and any artifacts needed to the ticket to show that the test is passing.

**Comment by ddavis-stsci** [comment]
Delivered

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-263?focusedCommentId=563323#comment-563323):_

Passed testing of SOC-604. The full output log is available in SOC_604_Full_Output.rtf, with SOC_604_DMS_Snippet.rtf containing just the DMS log messages. The individual DMS log messages are parsed out in the following files:
DMS_86_Log.rtf
DMS_87_Log.rtf
DMS_88_Log.rtf
DMS_89_Log.rtf

These tests are located in the test_level2_image_processing_pipeline function in /dms/local/roman/pipeline/pkgs/miniconda3/envs/romancal-0.5.0/lib/python3.9/site-packages/romancal/regtest/test_wfi_pipeline.py on the test machine.

The input data file for the pipeline is r0000201001001001001_01101_0001_WFI01_uncal.asdf, with the romancal output being r0000201001001001001_01101_0001_WFI01_cal.asdf. These files are located in the directory ████████████████████████████████████████████

To interact with a file, perform the following within python:
>>> import roman_datamodels as rdm
>>> cal = rdm.open('r0000201001001001001_01101_0001_WFI01_cal.asdf')

Then one can access the full metadata of cal with:
>>> print(cal.to_flat_dict())

The full metadata for the output file can be found in cal_metadata.rtf.

And then elements can be accessed directly, e.g.
>>> print(cal.meta.wcs)
will print the wcs object in the file. The wcs object for the output file is in wcs_object.rtf.

In addition, the wcs function can be run on a pixel to obtain the wcs information:
>>> print(cal.meta.wcs(2048,2048))
(85.0446586144039, -68.28210039308526)
