### ISSUE TITLE
Update code to suppress output from the jump step if not requested

### ISSUE THREAD

**Issue by ddavis-stsci** [spacetelescope/romancal#398]
For some reason the bot did not create an issue from RCAL-267

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-267](https://jira.stsci.edu/browse/RCAL-267)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-267?focusedCommentId=567924#comment-567924):_

#399
