### ISSUE TITLE
core schema should not be JWST specific information

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#40]
_Issue [RCAL-56](https://jira.stsci.edu/browse/RCAL-56) was created on JIRA by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey):_

The current core schema includes information that is specific only to JWST, this needs to be removed. Specifically under meta.exposure.type and meta.instrument.filter, but 

filter should be renamed to  'optical_element', and include only the roman element wheel options: 

F062

Engineering

Grism

Dark

F087

W146

F184

F158

Prism

F129

F106

 

I'm going to make a separate ticket to discuss the exptype information

**Comment by eslavich** [comment]
@PaulHuwe you updated the name of `filter` to `optical_element` in #33, but it looks like the enum values still need adjusting?

**Comment by PaulHuwe** [comment]
All those filters are already there (minus ENGINEERING and DARK). I will add those two.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494672#comment-494672):_

dont forget to remove JWST specific ones like "CLEAR"

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494688#comment-494688):_

I will remove CLEAR.

[Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) Can you confirm that "N/A, ANY, UNKNOWN" are needed for CRDS?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494694#comment-494694):_

They're only needed if we expect to have files with some kind of wildcard in `optical_element`.  The special values "N/A" and "ANY" both count as wildcards (with slightly different semantics) and will allow your dataset or reference file to match any value of `optical_element`.  I'd recommend leaving them out until we discover a need for them.

I don't think the "UNKNOWN" value has special meaning in CRDS.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494695#comment-494695):_

Thanks [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich), I will remove them all.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494701#comment-494701):_

For completeness, the following items should also be removed:

readpatt, nints, group_time, instrument.detector inclusion of ANY and N/A

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=494748#comment-494748):_

All changes made, awaiting PR submission.

**Comment by PaulHuwe** [comment]
Added to PR 33.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-56?focusedCommentId=497688#comment-497688):_

This was merged on 11/11/2020. I am closing this ticket.
