### ISSUE TITLE
Establish the basic set of exptype information for roman data

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#41]
_Issue [RCAL-57](https://jira.stsci.edu/browse/RCAL-57) was created on JIRA by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey):_

Agree on a basic set of exposure type information for Roman. This is a starting suggestion, and would populate meta.exposure.type
 * WFI_IMAGE
 * WFI_GRISM
 * WFI_PRISM
 * WFI_DARK
 * WFI_FLAT
 * WFI_TACQ
 * WFI_WFSC
 * WFI_GW

**Comment by PaulHuwe** [comment]
I change the enum values to these presently.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-57?focusedCommentId=494747#comment-494747):_

Changes are made, awaiting PR submission.

**Comment by PaulHuwe** [comment]
Added to PR 33.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-57?focusedCommentId=497687#comment-497687):_

PR 33 was merged on 11/11/2020. Resolving this issue.
