### ISSUE TITLE
Remove DataModel Object Copying

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#477]
_Issue [RCAL-329](https://jira.stsci.edu/browse/RCAL-329) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

The DQ Init step is the only step that could be creating a copy of the input datamodel - all other steps should simply modify their respective input datamodels instead of copying to another datamodel to work on.

**Comment by ddavis-stsci** [comment]
I can see how this works when the input data is opened in dq_init and the object is passed on. How should this work if the user runs the individual steps and the data is opened in the step? Do we need to add logic so the input files are opened with mode=’rw’?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-329?focusedCommentId=584440#comment-584440):_

Aren't input files already rw? I thought it was just ref riles that are locked down in the pipeline.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-329?focusedCommentId=584496#comment-584496):_

Paul, you are correct. I must have made an error when testing.

**Comment by ddavis-stsci** [comment]
Closing this. I put the wrong issue # in the PR - sigh.
