### ISSUE TITLE
discuss how to handle different numbers of guide window resultants

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#482]
_Issue [RCAL-333](https://jira.stsci.edu/browse/RCAL-333) was created on JIRA by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey):_

get together to discuss how to deal with the guide window data when there are different numbers of guide window resultants for each science resultant

 

<https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=ROMAN&title=Guide+Window+Discussion>

**Comment by ddavis-stsci** [comment]
The JIRA issue was closed Sept 26 closing this issue as well.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) on [JIRA](https://jira.stsci.edu/browse/RCAL-333?focusedCommentId=608712#comment-608712):_

discussion information linked in the confluence page

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-333?focusedCommentId=608713#comment-608713):_

The results of the discussion can be found at <https://innerspace.stsci.edu/pages/viewpage.action?pageId=314998296>
The example files are on central store as of 9/26/2022 at  ███████████████████████████████████████████████████████████████████████████████
