### ISSUE TITLE
Prepare for meetings with SSC

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#490]
_Issue [RCAL-338](https://jira.stsci.edu/browse/RCAL-338) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

There will be two tutorial days with SSC, on June 27th and July 1st.

These will cover ASDf and Roman datamodels.

This ticket is to track work on defining the details of the tutorials and writing them.

**Comment by ddavis-stsci** [comment]
Moved to the AL project and done.
