### ISSUE TITLE
guidewindow-1.0.0.yaml has wrong destination for gw_window_ystop 

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#524]
_Issue [RCAL-350](https://jira.stsci.edu/browse/RCAL-350) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Field gw_window_{*}ystop{*} lists destination as ScienceCommon.gw_window_{*}ystart{*}

**Comment by ddavis-stsci** [comment]
destination has been updated in RAD and merged.
