### ISSUE TITLE
Add test for stuserdict.py to roman_datamodels

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#532]
_Issue [RCAL-356](https://jira.stsci.edu/browse/RCAL-356) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Add a test for stuserdict.py to the test area for roman_datamodels.

**Comment by ddavis-stsci** [comment]
Code merged 29 Aug.
