### ISSUE TITLE
Add a test for filetype.py to roman_datamodels

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#533]
_Issue [RCAL-357](https://jira.stsci.edu/browse/RCAL-357) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Add a test for filetype.py to roman_datamodels to the test suite

**Comment by ddavis-stsci** [comment]
Code merged 29 Aug.
