### ISSUE TITLE
update pipeline for 100% saturation

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#535]
_Issue [RCAL-359](https://jira.stsci.edu/browse/RCAL-359) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The pipeline code should check after the saturation step is run that there are valid science data available for processing. If 100% of the science data is flagged as saturated print out an informational message and halt the pipeline.

**Comment by ddavis-stsci** [comment]
merged so closing

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-359?focusedCommentId=598699#comment-598699):_

#541
