### ISSUE TITLE
Rampfit step code to check for None from stcal code

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#536]
_Issue [RCAL-360](https://jira.stsci.edu/browse/RCAL-360) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The rampfit step code should check for the ramp code in stcal returning a None instead of an image/image description. In this case the data are all flagged as saturated and no further processing should occur. The step should write a message that the step failed with all the science pixels marked as saturated and the step should exit. This should be a rather rare corner case.

**Comment by ddavis-stsci** [comment]
Done and merged so closing this issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-360?focusedCommentId=598697#comment-598697):_

Resolved in #541
