### ISSUE TITLE
Add saturation check to test_wfi_pipeline code

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#537]
_Issue [RCAL-361](https://jira.stsci.edu/browse/RCAL-361) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The regression test for wfi_pipeline should have a check added for saturated data to show that the pipeline detects when all the science data is saturated and that the pipeline shuts down correctly.

**Comment by ddavis-stsci** [comment]
Merged so closing

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-361?focusedCommentId=598698#comment-598698):_

Resolved in #541
