### ISSUE TITLE
Update test_ramp_fitting for saturated images

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#538]
_Issue [RCAL-362](https://jira.stsci.edu/browse/RCAL-362) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Update the test_ramp_fitting regression test to include two tests for saturation. First if some user inputs data with all the science pixels flagged as saturated, print out an informational message saying that all the pixels are saturated and then halt.

The second case is where we have some ramps that are not marked as saturated but the stcal code identifies and marks these ramps as saturated leaving no valid data. The stcal code in this case returns None and the romancal ramp step should detect this and halt. The trick here will be to generate the input ramp data that stcal will mark as saturated. We may have to work with Ken or at least look at the JWST regression tests to generate the input. Maybe we can take a fully saturated image and alter a few ramps so that we can test this scenario. This should be a rare corner case.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-362?focusedCommentId=598471#comment-598471):_

I was able to implement the first test in RomanCAL PR-541: #541

I was unable to actually create a test for the second case - I reached out to Ken and he felt that there wasn't a way to make that case happen. Accordingly, I think we can close this ticket?

**Comment by ddavis-stsci** [comment]
After discussing this with the developers there does not seem to be a good test case for this so I'm closing this issue. If it shows up in the data we'll open a new ticket.
