### ISSUE TITLE
Add read noise to simulated images

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#575]
_Issue [RCAL-382](https://jira.stsci.edu/browse/RCAL-382) was created on JIRA by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly):_

Add read noise to simulated images.

Initial functionality to add Gaussian noise with amplitude given by a read noise image exists in the current simulator.  The following additional features are needed:
 * automatically grab read noise images from CRDS as appropriate, and plumb this into the simulator image rendering code
 * For L2 images, determine the appropriate amount of Poisson & read noise.  This depends on the details of the weighting of the pixels in the ramp fitting.  This ticket should cover an initial implementation that works in the read-noise dominated limit but is not optimal for bright sources.  This also means that the simulator needs to know something about the details of the multiaccum tables.

**Comment by ddavis-stsci** [comment]
closing this since rcal-382 is closed

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-382?focusedCommentId=628160#comment-628160):_

Addressed in <https://github.com/spacetelescope/romanisim/pull/34].>
