### ISSUE TITLE
Add persistence to simulated images

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#576]
_Issue [RCAL-383](https://jira.stsci.edu/browse/RCAL-383) was created on JIRA by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly):_

Add persistence to simulated images in the simulator.

galsim has a reasonable treatment of persistence already.  The main feature here is providing an interface that can handle the stream of past images needed to implement this feature.  I'd plan on adding an argument to the main image rendering code that gives the times when pixels accumulated very large numbers of counts and may be affected by persistence in the future.

**Comment by nden** [comment]
https://github.com/spacetelescope/romanisim/pull/37

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-383?focusedCommentId=632965#comment-632965):_

This is largely in in <https://github.com/spacetelescope/romanisim/pull/37],> but is currently hanging on permission from John to merge CR code.

**Comment by nden** [comment]
Oh, I saw the JIRA ticket was resolved.

**Comment by schlafly** [comment]
Sorry, the comment about CRs is from years ago; somehow your closing the ticket triggered it.  Thanks for closing.
