### ISSUE TITLE
Create Independent ModelContainer DataModel

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#578]
_Issue [RCAL-401](https://jira.stsci.edu/browse/RCAL-401) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Implement a "schema-less" ModelContainer datamodel in RDM. Implement it as a streamlined list of models, instantiated by a list of filenames, and with the model manipulate methods found in jwst.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-401?focusedCommentId=622256#comment-622256):_

Some work is here:
spacetelescope/roman_datamodels#115

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-401?focusedCommentId=623856#comment-623856):_

Tests are failing: <https://github.com/spacetelescope/roman_datamodels/actions/runs/3850743822/jobs/6561236816>

**Comment by ddavis-stsci** [comment]
Mairan merged issue so closing github issue

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-401?focusedCommentId=622256#comment-622256):_

Some work is here:
spacetelescope/roman_datamodels#115

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-401?focusedCommentId=622256#comment-622256):_

Some work is here:
spacetelescope/roman_datamodels#115
