### ISSUE TITLE
Association JSON File Support

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#580]
_Issue [RCAL-395](https://jira.stsci.edu/browse/RCAL-395) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Need to create methods to support instantiating an Association datamodel in RDM with a JSON file.

**Comment by ddavis-stsci** [comment]
This is fixed in https://jira.stsci.edu/browse/RCAL-468
Closing this issue.
