### ISSUE TITLE
Review associations suggested by RTB

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#581]
_Issue [RCAL-407](https://jira.stsci.edu/browse/RCAL-407) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Review the associations and association rules suggested by RTB

<https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=RI&title=Association+Rules+Drafting>

 

Define if the info for the rules is available in PSS so that the JWST association generator can be used.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-407?focusedCommentId=613580#comment-613580):_

I'm moving this back into the TODO column while RTB reviews their terminology and revises their proposed associations.

**Comment by ddavis-stsci** [comment]
Closing since rcal-407 is complete.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-407?focusedCommentId=613580#comment-613580):_

I'm moving this back into the TODO column while RTB reviews their terminology and revises their proposed associations.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-407?focusedCommentId=630756#comment-630756):_

RTB has reviewed and updated the terminology for the proposed Roman associations and coding is underway. Closing this issue and if there are more problems I'll file another ticket.
