### ISSUE TITLE
Create Associations DataModel

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#583]
_Issue [RCAL-387](https://jira.stsci.edu/browse/RCAL-387) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Create the initial datamodel for level 3 associations.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606007#comment-606007):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-101:
spacetelescope/roman_datamodels#101

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606089#comment-606089):_

This is on hold until use cases are defined better.

**Comment by ddavis-stsci** [comment]
I think this is solved in Mairan's PR
https://github.com/spacetelescope/romancal/pull/710 "Add ModelContainer to romancal.datamodels"
If there are more issues with the level 3 associations we can open a new ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606007#comment-606007):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-101:
spacetelescope/roman_datamodels#101

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606089#comment-606089):_

This is on hold until use cases are defined better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=648775#comment-648775):_

Pull request closed. Closing ticket, we are not doing more work on this.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606007#comment-606007):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-101:
spacetelescope/roman_datamodels#101

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=606089#comment-606089):_

This is on hold until use cases are defined better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-387?focusedCommentId=648775#comment-648775):_

Pull request closed. Closing ticket, we are not doing more work on this.
