### ISSUE TITLE
Set Up Testing Infrastructure in RomanISim

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#586]
_Issue [RCAL-389](https://jira.stsci.edu/browse/RCAL-389) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Set up pytest / tox /etc. in order to enable unit and regression testing in the simulator.

**Comment by ddavis-stsci** [comment]
RCAL-389 is closed and merged
