### ISSUE TITLE
Create ModelContainer DataModel

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#588]
_Issue [RCAL-386](https://jira.stsci.edu/browse/RCAL-386) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Create the datamodel for the level 3 container of models that associations will be used to populate.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-386?focusedCommentId=606008#comment-606008):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-102:
spacetelescope/roman_datamodels#102

**Comment by ddavis-stsci** [comment]
Closing this since https://github.com/spacetelescope/roman_datamodels/pull/102 is closed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-386?focusedCommentId=606008#comment-606008):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-102:
spacetelescope/roman_datamodels#102

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-386?focusedCommentId=632910#comment-632910):_

This was an early prototype and the work is closed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-386?focusedCommentId=606008#comment-606008):_

An initial implementation for discussion and planning this datamodel is available in RCAL PR-102:
spacetelescope/roman_datamodels#102

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-386?focusedCommentId=632910#comment-632910):_

This was an early prototype and the work is closed.
