### ISSUE TITLE
Cast to Units Before Removal

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/romancal#644]
For all quantities that get transferred to arrays for exporting to other libraries (e.g. STCAL), insert a unit conversion (to the library's expected units) first. E.g.

`code`
`data = data.to(u.DN).value`
`result = stcal.calibrate(data)`
`result = result * u.DN`
`more_code`

**Comment by ddavis-stsci** [comment]
RCAL-440 closed so closing this issue
