### ISSUE TITLE
Return warning for time object in random_utils

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#734]
_Issue [RCAL-539](https://jira.stsci.edu/browse/RCAL-539) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Catching the error when the time conversion is not valid (dubious year) is fine but we need to change the upper limit. To assume that the mission will end in 2030-01-01 is not reasonable. I'd remove the upper limit, catch the error and we also need to print out a log.warning. Anytime the code is not doing what the user expects we should let them know.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-539?focusedCommentId=648877#comment-648877):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis)  Is this still an issue and do we still need to catch the warning? This is the only open issue in the epic closing at the end of June.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-539?focusedCommentId=648893#comment-648893):_

This limitation is still in place,

 
```java
def generate_utc_timestamp(seed=None):
    # Random timestamp between 2020-01-01 and 2030-01-01
    return generate_float(1577836800.0, 1893456000.0, seed=seed)
```
As I recall this was causing an issue for someone using the tools to generate test data. 
We can close it until we get a better understanding of the problem, or add it to the Hack Day fixes?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-539?focusedCommentId=650351#comment-650351):_

"Close" means "done" in this project. May be "delete"? And open a ticket if we know something more concrete?

**Comment by ddavis-stsci** [comment]
Closing this until we get more information.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/RCAL-539?focusedCommentId=654101#comment-654101):_

This issue is entirely moot as <https://github.com/spacetelescope/roman_datamodels/pull/217,> which was part of [RCAL-588], removed all traces of `random_utils`.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-539?focusedCommentId=654176#comment-654176):_

I'm going through all tickets for the monthly report. Given the above comments, I'm closing this. Please reopen if there's more work to be done.
