### ISSUE TITLE
Tests for ramp_fitting

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#757]
_Issue [RCAL-512](https://jira.stsci.edu/browse/RCAL-512) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Implement unit and regression tests for ramp fitting.

**Comment by nden** [comment]
https://github.com/spacetelescope/romancal/pull/779/files
