### ISSUE TITLE
Rampfit test intermittently failing

### ISSUE THREAD

**Issue by WilliamJamieson** [spacetelescope/romancal#769]
The fix in #725 does not quite work all of the time, on the main branch I am getting intermittent failures in the
```
romancal/ramp_fitting/tests/test_ramp_fit.py::test_one_group_small_buffer_fit_ols
```
test cases. Iterative running of this test locally (it is skipped in CI) reproduces the error locally for me. For example I get the error:
```
E           AssertionError: 
E           Not equal to tolerance rtol=1e-06, atol=0
E           
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 1.06613152e-11
E           Max relative difference: 1.06613152e-06
E            x: array(-1.000001e-05, dtype=float32)
E            y: array(-1.e-05)
```

I believe the root of this error is: https://github.com/spacetelescope/romancal/blob/2396bc7bb78e00242e705ecb588157bf1a182f2a/romancal/ramp_fitting/tests/test_ramp_fit.py#L32-L36
The intermittent failure is caused by the fact that the data/err change from run-to-run of the tests. Instead, the random number generator should be seeded so that every test is exactly reproducible among different test runs.

**Comment by WilliamJamieson** [comment]
Note that this does not happen very often locally, but I can get it to reappear I think the issue is the very tight tolerances meaning larger fluctuations due to randomness occasionally escape the tolerances (notice how tiny the differences are above).

**Comment by schlafly** [comment]
I stumbled on this issue as well.  This test originally tested against the one pixel that was forced to have a value of 10, but in https://github.com/spacetelescope/romancal/pull/725 we changed that to point to a different pixel.  I think the real fix to 725 is a little different---the change to stcal meant that group_time started getting used, which is -99999 and causes an issue here.  I'll put in a fix for that soon, but I agree that seeding makes sense too.

**Comment by WilliamJamieson** [comment]
Yes, I am working through all of the romancal tests so that it uses the n[umpy random generators:](https://numpy.org/doc/stable/reference/random/generator.html) using an arbitrarily fixed seed.

**Comment by WilliamJamieson** [comment]
This does intermittently fail in the regression suite as well, see: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/268/testReport/junit/romancal.ramp_fitting.tests/test_ramp_fit/_stable_deps__test_one_group_small_buffer_fit_ols_none_/
