### ISSUE TITLE
investigate build error in regression tests

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#783]
_Issue [RCAL-610](https://jira.stsci.edu/browse/RCAL-610) was created on JIRA by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett):_

The Linux build of `romancal` on Jenkins appears to fail with an error upon running `pip install -e .[test,ephem]`

<https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2Fromancal/detail/romancal/994/pipeline/127/#step-128-log-388>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-610?focusedCommentId=653034#comment-653034):_

building succeeds locally with `pip install .`, but fails with `pip install .[test,ephem]`

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-610?focusedCommentId=653035#comment-653035):_

This might or might not be relevant; previous to the PEP621 change (moving build configuration from `setup.cfg` into `pyproject.toml`), the `ephem` extra was incorrectly configured in `setup.cfg`, so likely was not picked up by `setuptools` or `pip`:
<https://github.com/spacetelescope/romancal/blob/914c4072e03f93fb9a53c2240fe62536302e1ccb/setup.cfg#L63-L67>

Additionally, at that time I don't think `pip` warned if an extra was specified but did not exist in the configuration, so in that case running `pip install .[test,ephem]` in the regression tests would silently omit the `ephem` extra and proceed with just `test`.

**Comment by braingram** [comment]
If those deps are still used (searching from ephem and pymssql in romancal don't return anything beyond the pyproject.toml), it may help to pin cython to <3. It's recent release has broken many packages (pyyaml and likely pymssql).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-610?focusedCommentId=653043#comment-653043):_

the last successful build was #&#x2060;988 
<https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2Fromancal/detail/romancal/988/pipeline/127#step-128-log-88>

(the first failing build was #&#x2060;989)
<https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2Fromancal/detail/romancal/989/pipeline#step-128-log-226>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-610?focusedCommentId=653047#comment-653047):_

As I see it, the short-term solution would be to run the regtests without the `ephem` extra while we figure out how to get `pymssql-linux` to build within the environment again.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-610?focusedCommentId=653140#comment-653140):_

we removed usage of the `ephem` extra and the build is successful now (the tests still have some other errors but not related to this issue)
