### ISSUE TITLE
Regression tests failures due to missing WebbPSF data

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#865]
WebbPSF data does not appear to be available or configured for regression tests following #794
This is leading to failures in the regression tests.
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/349/pipeline/206#step-207-log-1507

**Comment by schlafly** [comment]
Thanks Brett.  @bmorris3 , this is what we talked about.  I think the Jenkins configuration can be used as a good model here.  https://github.com/spacetelescope/romanisim/blob/main/JenkinsfileRT_dev
