### ISSUE TITLE
Dark Unit Test Failure

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/romancal#934]
The removal of the `err` array is causing a dark unit test to fail. Specifically:

FAILED romancal/dark_current/tests/test_dark.py::test_dark_step_output_dark_file[WFI-WFI_IMAGE] - AttributeError: No such attribute (err) found in node

The `err` test lines simply need to be removed.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RCAL-693](https://jira.stsci.edu/browse/RCAL-693)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-693?focusedCommentId=667173#comment-667173):_

This is implemented in RCAL PR-938: #938

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-693?focusedCommentId=667604#comment-667604):_

PR approved and merged.
