### ISSUE TITLE
pytest test_psf fails for not having WEBBPSF_PATH set

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#942]
_Issue [RCAL-694](https://jira.stsci.edu/browse/RCAL-694) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Running

pytest romancal/lib/tests/test_psf.py

fails with

OSError: Environment variable $WEBBPSF_PATH is not set!

Suggestion: Mark test as skip if not set, or is there some default that can be used?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-694?focusedCommentId=672230#comment-672230):_

At the moment this test appears to do nothing

 
```java
pytest romancal/lib/tests/test_psf.py
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.0, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/ddavis/src/Roman/romancal
configfile: pyproject.toml
plugins: remotedata-0.4.0, asdf-2.15.0, hypothesis-6.82.0, doctestplus-0.13.0, cov-4.1.0, filter-subpackage-0.1.2, romancal-0.12.1.dev196+g9278535, mock-3.11.1, astropy-header-0.2.2, anyio-3.7.1, astropy-0.10.0, ci-watson-0.6.1, openfiles-0.5.0, env-0.8.2, arraydiff-0.5.0
collected 15 items
romancal/lib/tests/test_psf.py sssssssssssssss                                                                                                                                          [100%]
===================================================================================== 15 skipped
```
Maybe [Brett Morris](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bmmorris) knows more?

**Comment by schlafly** [comment]
They changed this so that you need to add a --webbpsf argument to pytest if you want the webbpsf tests to run.  I understand that plwishmaster & github add this argument.  e.g.
https://github.com/spacetelescope/romancal/actions/runs/6897893412/job/18766921406#step:10:186
This was done because webbpsf needs additional installation beyond pip install webbpsf (data files and environment variables), which can be annoying to get right.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Brett Morris](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bmmorris) on [JIRA](https://jira.stsci.edu/browse/RCAL-694?focusedCommentId=672264#comment-672264):_

Confirming [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly)'s comment above. If you add `--webbpsf` to the pytest call, it should work.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-694?focusedCommentId=676586#comment-676586):_

Closing this as there's a solution.
