### ISSUE TITLE
`test_resample_single_file` regression test failure

### ISSUE THREAD

**Issue by braingram** [spacetelescope/romancal#949]
The `test_resample_single_file` regression test is failing on the main branch.
```
FAILED romancal/regtest/test_resample.py::test_resample_single_file - AssertionError: {'arrays_differ': {"root['roman']['context']": {'abs_diff': 35304631148460,
...
```

This can be seen in the most recent romancal run (and other recent runs of other regression test workflows):
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2Fromancal/detail/romancal/1095/pipeline/215

**Comment by braingram** [comment]
@mairanteodoro is this related to #787?

**Comment by ddavis-stsci** [comment]
This appears to have been fixed, closing the issue.
