### ISSUE TITLE
jump step for the uneven fitting requires huge amounts of memory

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#966]
_Issue [RCAL-702](https://jira.stsci.edu/browse/RCAL-702) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Using data found in:

{{██████████████████████████████████████████

running the command

`strun romancal.step.RampFitStep random_dqinit.asdf`

on a m1 mac uses ~ 150GB of memory and takes ~5 minutes to run. This occurs regardless of the value of `use_jump_detection`.

The same data/command, using commits pre-jump detection, results in a runtime < 5 secs and not long enough to see memory usage in the activity monitor.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/RCAL-702?focusedCommentId=669607#comment-669607):_

I think I what is causing this, the code is retaining all of the individual fits from splitting the ramps across the dqflags in the case or jumps in the general case. The previous code was not doing this (which is entirely reasonable), and this change was added by me in order to get full diagnostic data on every fit made.

 [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) should we bother retaining the ability to retain this information for the future. This can be done with an optional argument, otherwise I can simply remove this.

An additional contributing factor is that it now sets the DQ flags for jump detection on every resultant, which we currently don’t have as part of the rampfit output model.

**Comment by schlafly** [comment]
Remind me: every fit result is something like 4 floats (slope, uncertainties) for certainly no more than the number of resultants, so this should make a maximum of 4 * 4 bytes * 4088^2 * 6?  I'm missing some large factor!  The old ramp code also had the individual segment fits in memory before averaging them down (split by the old jump detection), but that wasn't a big hit.  It's entirely possible that something's gone wrong with the romanisim / romancal interaction or something and we're splitting every resultant into as many segments as possible, but this number still seems like a lot.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-702?focusedCommentId=672217#comment-672217):_

Please close this if fixed with a link to the PR.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/RCAL-702?focusedCommentId=672252#comment-672252):_

Closed by: spacetelescope/stcal#226
